#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: sops | uninstall
  hosts: sops
  tasks:
  - include_role:
      name: sops
      tasks_from: uninstall.yml
